name: Markdown lint (project files)

on:
  pull_request:
    branches:
      - main
    paths:
      - .markdownlint.json
      - yarn.lock
      - '**/*.md'
      - .github/workflows/markdown-lint.yml
      - .github/workflows/markdownlint-problem-matcher.json


jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v28.0.0
        with:
          files: |
            **/*.md
          
      - name: Setup Node.js environment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - name: Lint markdown files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm install --location=global markdownlint-cli
          echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
          markdownlint ${{ steps.changed-files.outputs.all_changed_files }}
